### ISSUE TITLE
Osmocom SS7 stack and compatible hardware

### ISSUE THREAD

**Issue by analyserdmz** [0xc0decafe/ss7MAPer#1]
Hello,

thank you for giving out ss7MAPer, this is a great research booster for sure!

Could you please describe your setup, such as compatible SDR/USRP, and their setup instructions to be ready to work with ss7MAPer?

Thank you!

**Comment by 0xc0decafe** [comment]
Sorry, but you might be confusing things. SS7 has _nothing_ to do with Radio, so no SDR or USRP seen wide and far (; Instead you gonna need to connect to a SS7 gateway via MTP3 User Adaptation Layer (M3UA) protocol [RFC 4666] to get your messages into the SS7 world. You will find the [m3ua config](https://github.com/0xc0decafe/ss7MAPer/blob/288bd1ef4519b6185f3d594452894d6dc337ff76/config.example#L7) in the ss7MAPer config file.

best
